service: helloworld

frameworkVersion: ">=1.2.0 <2.48.0"

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  memorySize: 128
  timeout: 10
         

functions:
  main:
    handler: index.handler